version: "3.4"

services:
  keycloak:
    build:
      context: ./
      dockerfile: infrastructure/docker/keycloak/Dockerfile
      target: dev
    volumes:
      - ./themes/sankt-virtual:/opt/keycloak/themes/sankt-virtual
      - ./themes/noiV2:/opt/keycloak/themes/noiV2
      - ./registration-event-listener/target/registration-event-listener-0.0.1-SNAPSHOT.jar:/opt/keycloak/providers/registration-event-listener-0.0.1-SNAPSHOT.jar
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HTTP_RELATIVE_PATH: /auth
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - internal
      - authentication

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - internal

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    networks:
      - internal

networks:
  authentication:
    external: true
  internal:
    external: false
