# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

services:
  keycloak:
    build:
      context: ./
      dockerfile: infrastructure/docker/keycloak/Dockerfile
      target: dev
    environment:
      KC_LOG_LEVEL: info
      KC_CACHE_STACK: udp
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME_STRICT: 'false'
      KC_HTTP_ENABLED: 'true'
      KC_PROXY: 'passthrough'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    volumes:
      - ./themes/sankt-virtual:/opt/keycloak/themes/sankt-virtual
      - ./themes/noiV2:/opt/keycloak/themes/noiV2
      - ./themes/noi-community:/opt/keycloak/themes/noi-community
      #- ./native-s3-ping/target/native-s3-ping-jar-with-dependencies.jar:/opt/keycloak/providers/native-s3-ping-jar-with-dependencies.jar
      - ./registration-event-listener/target/registration-event-listener.jar:/opt/keycloak/providers/registration-event-listener.jar
    healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
      #test: timeout 10s bash -c ':> /dev/tcp/localhost/8080'
      test: "{ printf >&3 'GET /auth/realms/master/.well-known/openid-configuration HTTP/1.0\r\nHost: localhost\r\n\r\n'; cat <&3; } 3<>/dev/tcp/localhost/8080 | head -1 | grep 200"
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - internal
      - authentication

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - internal

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    networks:
      - internal

networks:
  authentication:
    external: true
  internal:
    external: false
